train: /content/traffic-sign-dataset-gtsrb-gtsdb/GTSRB/GTSRB/images/Train
val: /content/traffic-sign-dataset-gtsrb-gtsdb/GTSRB/GTSRB/images/Test
nc: 43

augmentation:
  mosaic: 1.0
  mixup: 0.5
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 45.0
  translate: 0.2
  scale: 0.5
  shear: 0.1
  perspective: 0.001

names:
  0: "Speed Limit 20 kmph"
  1: "Speed Limit 30 kmph"
  2: "Speed Limit 50 kmph"
  3: "Speed Limit 60 kmph"
  4: "Speed Limit 70 kmph"
  5: "Speed Limit 80 kmph"
  6: "End of Speed Limit 80 kmph"
  7: "Speed Limit 100 kmph"
  8: "Speed Limit 120 kmph"
  9: "No Passing"
  10: "No Passing vehicle over 3.5 ton"
  11: "Right-of-way at intersection"
  12: "Priority road"
  13: "Yield"
  14: "Stop"
  15: "No vehicles"
  16: "Veh > 3.5 tons prohibited"
  17: "No entry"
  18: "General caution"
  19: "Dangerous curve left"
  20: "Dangerous curve right"
  21: "Double curve"
  22: "Bumpy road"
  23: "Slippery road"
  24: "Road narrows on the right"
  25: "Road work"
  26: "Traffic signals"
  27: "Pedestrians"
  28: "Children crossing"
  29: "Bicycles crossing"
  30: "Beware of ice/snow"
  31: "Wild animals crossing"
  32: "End speed + passing limits"
  33: "Turn right ahead"
  34: "Turn left ahead"
  35: "Ahead only"
  36: "Go straight or right"
  37: "Go straight or left"
  38: "Keep right"
  39: "Keep left"
  40: "Roundabout mandatory"
  41: "End of no passing"
  42: "End no passing vehicle > 3.5 tons"